# Generated by Django 3.0.8 on 2022-03-19 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20220318_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredpost',
            name='status',
            field=models.IntegerField(choices=[('draft', 'Draft'), ('publish', 'Publish')], default=0),
        ),
        migrations.AlterField(
            model_name='mainpost',
            name='status',
            field=models.IntegerField(choices=[('draft', 'Draft'), ('publish', 'Publish')], default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[('draft', 'Draft'), ('publish', 'Publish')], default='draft'),
        ),
    ]
