# Generated by Django 3.0.8 on 2022-03-20 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20220320_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincomment',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
