# Generated by Django 3.0.8 on 2022-03-21 07:04

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('links', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
