# Generated by Django 3.0.8 on 2022-03-21 07:18

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_advertisement'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementThree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('links', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AdvertisementTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('links', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='Advertisement',
            new_name='AdvertisementOne',
        ),
    ]
