# Generated by Django 3.0.8 on 2022-03-23 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20220323_1015'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdvertisementTwo',
        ),
    ]
